all:
	sass --watch \
	sass/layout.sass:static/css/layout.css \
	sass/post.sass:static/css/post.css \
	sass/page.sass:static/css/page.css \
	sass/tag.sass:static/css/tag.css \
	sass/tags.sass:static/css/tags.css \
	sass/about.sass:static/css/about.css \
	--style compressed

clean:
	rm static/css -rf
